title: Juste OGODJA
logo: /assets/img/ori1.png
Description: ğŸ” **Ã€ la recherche dâ€™un stage opÃ©rateur Ã  partir de Juillet 2025**  
ğŸ“© **Contactez-moi pour toute opportunitÃ© !** ğŸš€ 
#show_downloads: true
theme: jekyll-theme-minimal
